export const speakers = [
  {
    id: 1,
    name: "Safia",
    surname: "Abdalla",
    img: "https://cache.sessionize.com/image/57d8-400o400o2-SDMEyKbxSF2GXexsFunXcE.jpeg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 2,
    name: "David",
    surname: "Fowler",
    img: "https://cache.sessionize.com/image/89e0-400o400o2-463198c3-6d0b-4485-a4fc-631b4943d29d.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 3,
    name: "Scott",
    surname: "Hanselman",
    img: "https://cache.sessionize.com/image/f40d-400o400o2-4P6NeCk4VSRKPAbycZoj1k.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 5,
    name: "David",
    surname: "Fowler",
    img: "https://cache.sessionize.com/image/89e0-400o400o2-463198c3-6d0b-4485-a4fc-631b4943d29d.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 8,
    name: "David",
    surname: "Fowler",
    img: "https://cache.sessionize.com/image/89e0-400o400o2-463198c3-6d0b-4485-a4fc-631b4943d29d.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 6,
    name: "Scott",
    surname: "Hanselman",
    img: "https://cache.sessionize.com/image/f40d-400o400o2-4P6NeCk4VSRKPAbycZoj1k.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 7,
    name: "Safia",
    surname: "Abdalla",
    img: "https://cache.sessionize.com/image/57d8-400o400o2-SDMEyKbxSF2GXexsFunXcE.jpeg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 4,
    name: "Safia",
    surname: "Abdalla",
    img: "https://cache.sessionize.com/image/57d8-400o400o2-SDMEyKbxSF2GXexsFunXcE.jpeg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 9,
    name: "Scott",
    surname: "Hanselman",
    img: "https://cache.sessionize.com/image/f40d-400o400o2-4P6NeCk4VSRKPAbycZoj1k.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 10,
    name: "Scott",
    surname: "Hanselman",
    img: "https://cache.sessionize.com/image/f40d-400o400o2-4P6NeCk4VSRKPAbycZoj1k.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 11,
    name: "Safia",
    surname: "Abdalla",
    img: "https://cache.sessionize.com/image/57d8-400o400o2-SDMEyKbxSF2GXexsFunXcE.jpeg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 12,
    name: "Safia",
    surname: "Abdalla",
    img: "https://cache.sessionize.com/image/57d8-400o400o2-SDMEyKbxSF2GXexsFunXcE.jpeg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
  {
    id: 13,
    name: "Scott",
    surname: "Hanselman",
    img: "https://cache.sessionize.com/image/f40d-400o400o2-4P6NeCk4VSRKPAbycZoj1k.jpg",
    url: "https://google.com",
    username: "@safia",
    bio: "Software Engineer on the ASP.NET Core team",
  },
];
