export const agenda = [
  {
    id: 1,
    title: "Day 1",
    subtitle: "Tuesday, November 14",
    sessions: [
      {
        id: 1,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 2,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 3,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Day 2",
    subtitle: "Wednesday, November 15",
    sessions: [
      {
        id: 1,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 2,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 3,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Day 3",
    subtitle: "Thursday, November 16",
    sessions: [
      {
        id: 1,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 2,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 3,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
    ],
  },
];
