export const agenda = [
  {
    id: 1,
    title: "Day 1",
    subtitle: "Tuesday, November 14",
    sessions: [
      {
        id: 1,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 2,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 3,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Day 2",
    subtitle: "Wednesday, November 15",
    sessions: [
      {
        id: 1,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 2,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 3,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Day 3",
    subtitle: "Thursday, November 16",
    sessions: [
      {
        id: 1,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 2,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
      {
        id: 3,
        timeFrom: "9:00 PM",
        timeTo: "10:00 PM",
        timezoneOffset: "GMT+5",
        title: "Welcome to .NET 8",
        description:
          ".NET 8 is here! Find out what is new for .NET developers across all workloads including cloud, mobile, desktop, web, AI, IoT, and so much more.",
        speakers: [
          "Damian",
          "Edwards",
          "Safia",
          "Abdalla",
          "David",
          "Fowler",
          "Gaurav",
          "Seth",
          "Daniel",
          "Roth",
          "Glenn",
          "Condron",
          "Maddy",
          "Montaquila",
          "Maria",
          "Naggaga",
        ],
      },
    ],
  },
];

export const speakers = [
  {
    id: 1,
    name: "Martin",
    surname: "Tatar",
    img: "/images/speakers/martin-tatar.jpg",
    position: "Community Builder at Microsoft",
    isFeatured: true,
    url: "https://www.linkedin.com/in/martintatar/",
    username: "martintatar",
  },
  {
    id: 2,
    name: "Hassan",
    surname: "Habib",
    img: "/images/speakers/hassan-habib.jpg",
    position: "Innovator, Engineer and Entrepreneur",
    isFeatured: true,
    url: "https://www.linkedin.com/in/hassanrezkhabib/",
    username: "hassanrezkhabib",
  },
  {
    id: 3,
    name: "Djakhongir",
    surname: "Makhkamov",
    img: "/images/speakers/djakhongir-makhkamov.jpg",
    position: "Tech Lead Ex Amazon",
    isFeatured: true,
    url: "https://www.linkedin.com/in/djahon/",
    username: "djahon",
  },
  {
    id: 4,
    name: "Bobur",
    surname: "Umurzokov",
    img: "/images/speakers/bobur-umurzokov.jpg",
    position: "ex-Microsoft Developer Audience Lead",
    isFeatured: true,
    url: "https://www.linkedin.com/in/boburumurzokov/",
    username: "boburumurzokov",
  },
  {
    id: 5,
    name: "Milan",
    surname: "Jovanović",
    img: "/images/speakers/milan-jovanovic.jpg",
    position: "Microsoft MVP",
    isFeatured: true,
    url: "https://www.linkedin.com/in/milan-jovanovic/",
    username: "milan-jovanovic",
  },
  {
    id: 6,
    name: "Doniyor",
    surname: "Niyozov",
    img: "/images/speakers/doniyor-niyozov.jpg",
    position: "Lead Engineer at Silk Road",
    isFeatured: true,
    url: "https://www.linkedin.com/in/doniyor-niyozov-380a59135",
    username: "doniyor-niyozov",
  },
  {
    id: 7,
    name: "Oybek",
    surname: "Jumaniyozov",
    img: "/images/speakers/oybek-jumaniyozov.jpg",
    position: "Platform Architect at Medyear",
    isFeatured: true,
    url: "https://www.linkedin.com/in/oybekjumaniyozov",
    username: "oybekjumaniyozov",
  },
  {
    id: 8,
    name: "Nozim",
    surname: "Turakulov",
    img: "/images/speakers/nozim-turakulov.jpg",
    position: "Lead .Net Engineer at Opinov8",
    isFeatured: true,
    url: "https://www.linkedin.com/in/nozimturakulov/",
    username: "nozimturakulov",
  },
  {
    id: 9,
    name: "Izzatkhon",
    surname: "Shamsiev",
    img: "/images/speakers/izzatkhon-shamsiev.jpg",
    position: "Lead .NET Engineer at EPAM Systems",
    isFeatured: true,
    url: "https://www.linkedin.com/in/izzatkhon",
    username: "izzatkhon",
  },
];

export const swags = [
  {
    id: 1,
    title: "Free Swag",
    description:
      "Have fun with these free swag items. Show them off on Twitter using #mcdconfuz2023",
    linkTitle: "View on GitHub",
    linkUrl: "/swag",
  },
  {
    id: 2,
    title: "Sponsor swag bag",
    description:
      "Enter to win 1 of 25 swag bags with prizes from our sponsors.",
    linkTitle: "Enter to win",
    linkUrl: "/swag",
  },
  {
    id: 3,
    title: "Challenges",
    description:
      "Participate for a chance to win an awesome price from our sponsors.",
    linkTitle: "Find the clues",
    linkUrl: "/swag",
  },
];

export const headerLinks = [
  {
    id: 1,
    title: "Home",
    slug: "/",
  },
  {
    id: 2,
    title: "Speakers",
    slug: "speakers",
  },
  {
    id: 3,
    title: "Agenda",
    slug: "agenda",
  },
];

export const footerLinks = [
  {
    id: 1,
    title: "Powered by .NET 8.0.0",
    url: "#",
  },
  {
    id: 2,
    title: "Privacy Policy",
    url: "https://go.microsoft.com/fwlink/?LinkId=521839",
  },
  {
    id: 3,
    title: "Code of Conduct",
    url: "code-of-conduct",
  },
  {
    id: 4,
    title: "© 2023 Microsoft",
    url: "https://microsoft.com/",
  },
];

export const features = [
  {
    id: 1,
    title: "The Biggest Microsoft Event in Uzbekistan",
    description:
      "Our Microsoft Conference in Uzbekistan is making its debut this year as an in-person event. We're excited to bring you an exceptional conference experience that celebrates innovation and collaboration. We are dedicated to providing a world-class, engaging event for all attendees. As we embark on this journey, we aim to connect with technology enthusiasts, industry experts, and businesses across Uzbekistan and beyond. Join us as we kickstart this inaugural event and make history together.",
  },
  {
    id: 2,
    title: "What to expect at the conference",
    description:
      "In just one day, our conference brings together .NET gurus like Hassan Habib, Djakhongir Makhkamov, Martin Tatar, and more. You'll gain invaluable insights and advice from these experts, plus the chance to network with fellow enthusiasts. And that's not all! Attendees can look forward to exciting giveaways, unforgettable gifts, and ample networking opportunities. Best of all, you can ask any questions!",
  },
];

export const schedule = [
  {
    id: 1,
    title: ".NET 8 release",
    description:
      "Stay tuned for exciting news about .NET 8! Join the .NET team to discover all the new possibilities with our latest release.",
  },
  {
    id: 2,
    title: "Networking",
    description:
      "Connect and network with industry peers at our conference, fostering valuable relationships and collaborations.",
  },
  {
    id: 3,
    title: "Feel the vibe",
    description:
      "Immerse yourself in the conference vibe with a complimentary lunch, exciting gifts, and the latest news.",
  },
];

export const sponsors = [
  {
    id: 1,
    title: "Digital Generation Uzbekistan",
    lightImg: "/images/sponsors/dg.svg",
    darkImg: "/images/sponsors/dg.svg",
    imgWidth: 256,
    imgHeight: 124,
    link: "https://digitalgeneration.uz/uz/",
  },
  {
    id: 2,
    title: "Microsoft developers community in Uzbekistan",
    lightImg: "/images/sponsors/mdcu.svg",
    darkImg: "/images/sponsors/mdcu.svg",
    imgWidth: 256,
    imgHeight: 124,
    link: "https://microsoft.com",
  },
];
